simulator_addr: 127.0.0.1:9999
sms_file: data/sms.data
mms_addr: http://127.0.0.1:9999/mms
mms_file: data/mms.json
voice_call_file: data/voice.data
email_file: data/email.data
billing_file: data/billing.data
support_addr: http://127.0.0.1:9999/support
support_file: data/support.json
incident_addr: http://127.0.0.1:9999/incident
incident_file: data/incident.json